project:
  type: default
  output-dir: output
  pre-render: scripts/ensure_quarto_python.sh

jupyter: dod2k-cfr

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    number-sections: true
    code-fold: false
    code-tools: true

execute:
  freeze: auto
  warning: false
  message: false

lang: en
